### ISSUE TITLE
How is instance name determined?

### ISSUE THREAD

**Issue by djw8605** [opensciencegrid/gracc#3]
How is the instance name determined.  In the docs:

> Most strings will expand the text %I to the "instance name".  So, for the `osg` instance, the following,

But, how is the instance name determined?

**Comment by bbockelm** [comment]
If you have a service file named something like `foo@.service`, then systemd will refuse to do `systemctl start foo`; rather, the sysadmin must provide an instance name on the command line: `systemctl start foo@osg`.

**Comment by zvada** [comment]
I guess this is not needed for any purpose here anymore, is it or can we close? @djw8605 @bbockelm ?
